### ISSUE TITLE
Not sure what to do

### ISSUE THREAD

**Issue by Haleymiranda79** [yassinetb/Lex-Fridman-Podcast#2]
The READ ME does not tell you how to install it. What do I do first?

**Comment by yassinetb** [comment]
Hello @Haleymiranda79, thanks for reaching out.

Unfortunately, this has not been developed as a library to install.  Though you are free to pull the code and use it to your liking. You should find all the necessary information about how to use my code on the README. 

Hope this helps.

**Comment by Haleymiranda79** [comment]
Thanks
